# Use def to define favourite_book then add a message... 
def favorite_book(title):
    print(f"One of my favorite books is {title}.")

# Call the function with the book title to display the statement...
favorite_book("Alice in Wonderland")