age = 367
if age < 2: # Baby...
    print("You're a Baby")
elif age < 4: # Toddler...
    print("You're a Toddler")
elif age < 13: # Kid...
    print("You're a Kid")
elif age < 20: # Teenager...
    print("You're a Teenager")
elif age < 65: # Adult...
    print("You're an Adult")
else: # Elder... 
    print("You're an Elder")